In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('bike_share_yr_0.csv')
df2=pd.read_csv('bike_share_yr_1.csv')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17290 entries, 0 to 17289
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      17290 non-null  object
 1   season      17290 non-null  int64
 2   yr          17290 non-null  int64
 3   mnth        17290 non-null  int64
 4   hr          17290 non-null  int64
 5   holiday     17290 non-null  int64
 6   weekday     17290 non-null  int64
 7   workingday  17290 non-null  int64
 8   weathersit  17290 non-null  int64
 9   temp        17290 non-null  float64
 10  atemp       17290 non-null  float64
 11  hum         17290 non-null  float64
 12  windspeed   17290 non-null  float64
 13  rider_type  17290 non-null  object
 14  riders      17290 non-null  int64
dtypes: float64(4), int64(9), object(2)
memory usage: 2.0+ MB

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17468 entries, 0 to 17467
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      17468 non-null  object
 1   season      17468 non-null  int64
 2   yr          17468 non-null  int64
 3   mnth        17468 non-null  int64
 4   hr          17468 non-null  int64
 5   holiday     17468 non-null  int64
 6   weekday     17468 non-null  int64
 7   workingday  17468 non-null  int64
 8   weathersit  17468 non-null  int64
 9   temp        17468 non-null  float64
 10  atemp       17468 non-null  float64
 11  hum         17468 non-null  float64
 12  windspeed   17468 non-null  float64
 13  rider_type  17468 non-null  object
 14  riders      17468 non-null  int64
dtypes: float64(4), int64(9), object(2)
memory usage: 2.0+ MB

In [10]:
missing = df1.isnull().sum().sort_values(ascending=False)
print(missing)

dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
rider_type    0
riders        0
dtype: int64

In [11]:
missing = df2.isnull().sum().sort_values(ascending=False)
print(missing)

dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
rider_type    0
riders        0
dtype: int64

In [14]:
duplicates = df1.duplicated().sum()
print(f"Total duplicates: {duplicates}")

Total duplicates: 0

In [15]:
duplicates = df2.duplicated().sum()
print(f"Total duplicates: {duplicates}")

Total duplicates: 0

In [17]:
categorical_cols = ['season', 'holiday', 'weekday', 'workingday', 'weathersit', 'rider_type']

for col in categorical_cols:
    print(f"\n{col} unique values:")
    print(df1[col].unique())

season unique values:
[1 2 3 4]

holiday unique values:
[0 1]

weekday unique values:
[6 0 1 2 3 4 5]

workingday unique values:
[0 1]

weathersit unique values:
[1 2 3 4]

rider_type unique values:
['casual' 'registered']

In [18]:
categorical_cols = ['season', 'holiday', 'weekday', 'workingday', 'weathersit', 'rider_type']

for col in categorical_cols:
    print(f"\n{col} unique values:")
    print(df2[col].unique())

season unique values:
[1 2 3 4]

holiday unique values:
[0 1]

weekday unique values:
[0 1 2 3 4 5 6]

workingday unique values:
[0 1]

weathersit unique values:
[1 2 3 4]

rider_type unique values:
['casual' 'registered']

In [20]:
# If holiday = 1 → workingday should be 0
df1[(df1['holiday'] == 1) & (df1['workingday'] == 1)]

Empty DataFrame
Columns: [dteday, season, yr, mnth, hr, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed, rider_type, riders]
Index: []

In [21]:
# If holiday = 1 → workingday should be 0
df2[(df2['holiday'] == 1) & (df2['workingday'] == 1)]

Empty DataFrame
Columns: [dteday, season, yr, mnth, hr, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed, rider_type, riders]
Index: []

In [22]:
df1.head()

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,rider_type,riders
0,1/1/2021,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,casual,3
1,1/1/2021,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,casual,8
2,1/1/2021,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,casual,5
3,1/1/2021,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,casual,3
4,1/1/2021,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,casual,0

In [23]:
df1['dteday'].unique()

array(['1/1/2021', '2/1/2021', '3/1/2021', '4/1/2021', '5/1/2021',
       '6/1/2021', '7/1/2021', '8/1/2021', '9/1/2021', '10/1/2021',
       '11/1/2021', '12/1/2021', '13/1/2021', '14/1/2021', '15/1/2021',
       '16/1/2021', '17/1/2021', '18/1/2021', '19/1/2021', '20/1/2021',
       '21/1/2021', '22/1/2021', '23/1/2021', '24/1/2021', '25/1/2021',
       '26/1/2021', '27/1/2021', '28/1/2021', '29/1/2021', '30/1/2021',
       '31/1/2021', '1/2/2021', '2/2/2021', '3/2/2021', '4/2/2021',
       '5/2/2021', '6/2/2021', '7/2/2021', '8/2/2021', '9/2/2021',
       '10/2/2021', '11/2/2021', '12/2/2021', '13/2/2021', '14/2/2021',
       '15/2/2021', '16/2/2021', '17/2/2021', '18/2/2021', '19/2/2021',
       '20/2/2021', '21/2/2021', '22/2/2021', '23/2/2021', '24/2/2021',
       '25/2/2021', '26/2/2021', '27/2/2021', '28/2/2021', '1/3/2021',
       '2/3/2021', '3/3/2021', '4/3/2021', '5/3/2021', '6/3/2021',
       '7/3/2021', '8/3/2021', '9/3/2021', '10/3/2021', '11/3/2021',
       '12/3/2021', '13/3/2021', '14/3/2021', '15/3/2021', '16/3/2021',
       '17/3/2021', '18/3/2021', '19/3/2021', '20/3/2021', '21/3/2021',
       '22/3/2021', '23/3/2021', '24/3/2021', '25/3/2021', '26/3/2021',
       '27/3/2021', '28/3/2021', '29/3/2021', '30/3/2021', '31/3/2021',
       '1/4/2021', '2/4/2021', '3/4/2021', '4/4/2021', '5/4/2021',
       '6/4/2021', '7/4/2021', '8/4/2021', '9/4/2021', '10/4/2021',
       '11/4/2021', '12/4/2021', '13/4/2021', '14/4/2021', '15/4/2021',
       '16/4/2021', '17/4/2021', '18/4/2021', '19/4/2021', '20/4/2021',
       '21/4/2021', '22/4/2021', '23/4/2021', '24/4/2021', '25/4/2021',
       '26/4/2021', '27/4/2021', '28/4/2021', '29/4/2021', '30/4/2021',
       '1/5/2021', '2/5/2021', '3/5/2021', '4/5/2021', '5/5/2021',
       '6/5/2021', '7/5/2021', '8/5/2021', '9/5/2021', '10/5/2021',
       '11/5/2021', '12/5/2021', '13/5/2021', '14/5/2021', '15/5/2021',
       '16/5/2021', '17/5/2021', '18/5/2021', '19/5/2021', '20/5/2021',
       '21/5/2021', '22/5/2021', '23/5/2021', '24/5/2021', '25/5/2021',
       '26/5/2021', '27/5/2021', '28/5/2021', '29/5/2021', '30/5/2021',
       '31/5/2021', '1/6/2021', '2/6/2021', '3/6/2021', '4/6/2021',
       '5/6/2021', '6/6/2021', '7/6/2021', '8/6/2021', '9/6/2021',
       '10/6/2021', '11/6/2021', '12/6/2021', '13/6/2021', '14/6/2021',
       '15/6/2021', '16/6/2021', '17/6/2021', '18/6/2021', '19/6/2021',
       '20/6/2021', '21/6/2021', '22/6/2021', '23/6/2021', '24/6/2021',
       '25/6/2021', '26/6/2021', '27/6/2021', '28/6/2021', '29/6/2021',
       '30/6/2021', '1/7/2021', '2/7/2021', '3/7/2021', '4/7/2021',
       '5/7/2021', '6/7/2021', '7/7/2021', '8/7/2021', '9/7/2021',
       '10/7/2021', '11/7/2021', '12/7/2021', '13/7/2021', '14/7/2021',
       '15/7/2021', '16/7/2021', '17/7/2021', '18/7/2021', '19/7/2021',
       '20/7/2021', '21/7/2021', '22/7/2021', '23/7/2021', '24/7/2021',
       '25/7/2021', '26/7/2021', '27/7/2021', '28/7/2021', '29/7/2021',
       '30/7/2021', '31/7/2021', '1/8/2021', '2/8/2021', '3/8/2021',
       '4/8/2021', '5/8/2021', '6/8/2021', '7/8/2021', '8/8/2021',
       '9/8/2021', '10/8/2021', '11/8/2021', '12/8/2021', '13/8/2021',
       '14/8/2021', '15/8/2021', '16/8/2021', '17/8/2021', '18/8/2021',
       '19/8/2021', '20/8/2021', '21/8/2021', '22/8/2021', '23/8/2021',
       '24/8/2021', '25/8/2021', '26/8/2021', '27/8/2021', '28/8/2021',
       '29/8/2021', '30/8/2021', '31/8/2021', '1/9/2021', '2/9/2021',
       '3/9/2021', '4/9/2021', '5/9/2021', '6/9/2021', '7/9/2021',
       '8/9/2021', '9/9/2021', '10/9/2021', '11/9/2021', '12/9/2021',
       '13/9/2021', '14/9/2021', '15/9/2021', '16/9/2021', '17/9/2021',
       '18/9/2021', '19/9/2021', '20/9/2021', '21/9/2021', '22/9/2021',
       '23/9/2021', '24/9/2021', '25/9/2021', '26/9/2021', '27/9/2021',
       '28/9/2021', '29/9/2021', '30/9/2021', '1/10/2021', '2/10/2021',
       '3/10/2021', '4/10/2021', '5/10/2021', '6/10/2021', '7/10/2021',
       '8/10/2021', '9/10/2021', '10/10/2021', '11/10/2021', '12/10/2021',
       '13/10/2021', '14/10/2021', '15/10/2021', '16/10/2021',
       '17/10/2021', '18/10/2021', '19/10/2021', '20/10/2021',
       '21/10/2021', '22/10/2021', '23/10/2021', '24/10/2021',
       '25/10/2021', '26/10/2021', '27/10/2021', '28/10/2021',
       '29/10/2021', '30/10/2021', '31/10/2021', '1/11/2021', '2/11/2021',
       '3/11/2021', '4/11/2021', '5/11/2021', '6/11/2021', '7/11/2021',
       '8/11/2021', '9/11/2021', '10/11/2021', '11/11/2021', '12/11/2021',
       '13/11/2021', '14/11/2021', '15/11/2021', '16/11/2021',
       '17/11/2021', '18/11/2021', '19/11/2021', '20/11/2021',
       '21/11/2021', '22/11/2021', '23/11/2021', '24/11/2021',
       '25/11/2021', '26/11/2021', '27/11/2021', '28/11/2021',
       '29/11/2021', '30/11/2021', '1/12/2021', '2/12/2021', '3/12/2021',
       '4/12/2021', '5/12/2021', '6/12/2021', '7/12/2021', '8/12/2021',
       '9/12/2021', '10/12/2021', '11/12/2021', '12/12/2021',
       '13/12/2021', '14/12/2021', '15/12/2021', '16/12/2021',
       '17/12/2021', '18/12/2021', '19/12/2021', '20/12/2021',
       '21/12/2021', '22/12/2021', '23/12/2021', '24/12/2021',
       '25/12/2021', '26/12/2021', '27/12/2021', '28/12/2021',
       '29/12/2021', '30/12/2021', '31/12/2021'], dtype=object)

In [27]:
pd.to_datetime(df1['dteday'], errors='coerce')

0       2021-01-01
1       2021-01-01
2       2021-01-01
3       2021-01-01
4       2021-01-01
           ...
17285          NaT
17286          NaT
17287          NaT
17288          NaT
17289          NaT
Name: dteday, Length: 17290, dtype: datetime64[ns]

In [28]:
pd.to_datetime(df1['dteday'], format='%d/%m/%Y')

0       2021-01-01
1       2021-01-01
2       2021-01-01
3       2021-01-01
4       2021-01-01
           ...
17285   2021-12-31
17286   2021-12-31
17287   2021-12-31
17288   2021-12-31
17289   2021-12-31
Name: dteday, Length: 17290, dtype: datetime64[ns]